version: '2'
services:
  web:
    image: webdevops/php-apache-dev
    links:
      - db
    ports:
      - 80:80
    volumes:
      - ./CODE/:/app
 
  db:
    image: mysql:5.7
    volumes:
      - ./.data/mysql:/var/lib/mysql