<?php
//$res->module('thijzer/blog')->scope('blog@recentArticles');
$res->scope('blog@index');
//$res->scope('blog@recentArticles');
$res->block('content')->html('blog/articles');
$res->block('sidebar')->html('blog/recentArticles');
$res->block('sidebar')->html('blog/recentCategories');
$res->block('sidebar')->html('users/loggedIn');
$res->block('content')->html('pagination');
